### ISSUE TITLE
New "history" permission?

### ISSUE THREAD

**Issue by noelleleigh** [mpod/mPage#12]
Could you explain why the new update for mPage requires a new permission?

**Comment by mpod** [comment]
It's a very important question, and thank you for asking it.
New permissions is needed because of this [line](https://github.com/mpod/mPage/blob/master/src/scripts/view.js#L468).
In recent commit I added support for opening links in reader mode, but in that case the opened links would not be marked as visited in browser's history. So I needed to mark them manually, which requested 'history' permission.
I'm ready to remove this feature if there will be further privacy concerns.

**Comment by lionirdeadman** [comment]
I think explaining the permissions in the Firefox addon marketplace and the readme would be probably be something that we'd want to do as to make users comfortable with it.

**Comment by mpod** [comment]
Good idea... I added explanation for requested permissions to readme file and addon marketplace.
