### ISSUE TITLE
Doesn't Work On Waterfox For https://www.animationscoop.com/feed

### ISSUE THREAD

**Issue by neurodiverseEsoteric** [mpod/mPage#18]
![Screen Shot 2021-06-27 at 20 01 59 Crop](https://user-images.githubusercontent.com/577091/123573580-151f6a00-d783-11eb-8d2b-d828fc5cc92b.png)

Happens even in a blank profile with just this addon...

**Comment by mpod** [comment]
Feed is unfortunately invalid. It contains some garbage at the end of the file. 
Since the file is partially valid, I implemented a workaround for such errors. New version of add-on is waiting for approval. Usually it is quickly approved, but today a message popped up saying that it may take 3-4 weeks. 
Thank you for using the add-on.

**Comment by mpod** [comment]
New version is approved by mozilla.

**Comment by neurodiverseEsoteric** [comment]
Thanks for continuing to work on the addon!
